port: 9000

logging:
  format: "text" # if you set value 'json' format will be changed to JSON, else will be used default format
  logfile: false # if you want to put logs to log file set true; if you set 'false' logs will out in console

auth:
  salt: "your_salt"
  signing_key: "your_signing_key"
  token_ttl: 744

db:
  username: "postgres"
  password: "" # you must be type DB_PASSWORD=pass in .env file
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"